using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace P1611706.Model
{
    public class COPTG
	{
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
		public string CREATE_DATE { get; set; }
		public string MODIFIER { get; set; }
		public string MODI_DATE { get; set; }
		public Decimal FLAG { get; set; }
		public string CREATE_TIME { get; set; }
		public string MODI_TIME { get; set; }
		public string TRANS_TYPE { get; set; }
		public string TRANS_NAME { get; set; }
		public string sync_date { get; set; }
		public string sync_time { get; set; }
		public string sync_mark { get; set; }
		public Decimal sync_count { get; set; }
		public string DataUser { get; set; }
		public string DataGroup { get; set; }
		public string TG001 { get; set; }
		public string TG002 { get; set; }
		public string TG003 { get; set; }
		public string TG004 { get; set; }
		public string TG005 { get; set; }
		public string TG006 { get; set; }
		public string TG007 { get; set; }
		public string TG008 { get; set; }
		public string TG009 { get; set; }
		public string TG010 { get; set; }
		public string TG011 { get; set; }
		public Decimal TG012 { get; set; }
		public Decimal TG013 { get; set; }
		public string TG014 { get; set; }
		public string TG015 { get; set; }
		public string TG016 { get; set; }
		public string TG017 { get; set; }
		public string TG018 { get; set; }
		public string TG019 { get; set; }
		public string TG020 { get; set; }
		public string TG021 { get; set; }
		public Decimal TG022 { get; set; }
		public string TG023 { get; set; }
		public string TG024 { get; set; }
		public Decimal TG025 { get; set; }
		public string TG026 { get; set; }
		public string TG027 { get; set; }
		public string TG028 { get; set; }
		public string TG029 { get; set; }
		public string TG030 { get; set; }
		public string TG031 { get; set; }
		public Decimal TG032 { get; set; }
		public Decimal TG033 { get; set; }
		public string TG034 { get; set; }
		public string TG035 { get; set; }
		public string TG036 { get; set; }
		public string TG037 { get; set; }
		public string TG038 { get; set; }
		public string TG039 { get; set; }
		public string TG040 { get; set; }
		public Decimal TG041 { get; set; }
		public string TG042 { get; set; }
		public string TG043 { get; set; }
		public Decimal TG044 { get; set; }
		public Decimal TG045 { get; set; }
		public Decimal TG046 { get; set; }
		public string TG047 { get; set; }
		public string TG048 { get; set; }
		public string TG049 { get; set; }
		public string TG050 { get; set; }
		public string TG051 { get; set; }
		public Decimal TG052 { get; set; }
		public Decimal TG053 { get; set; }
		public Decimal TG054 { get; set; }
		public string TG055 { get; set; }
		public string TG056 { get; set; }
		public string TG057 { get; set; }
		public string TG058 { get; set; }
		public string TG059 { get; set; }
		public string TG060 { get; set; }
		public string TG061 { get; set; }
		public string TG062 { get; set; }
		public Decimal TG063 { get; set; }
		public string TG064 { get; set; }
		public string TG065 { get; set; }
		public string TG066 { get; set; }
		public string TG067 { get; set; }
		public string TG068 { get; set; }
		public Decimal TG069 { get; set; }
		public string TG070 { get; set; }
		public Decimal TG071 { get; set; }
		public string TG072 { get; set; }
		public string TG073 { get; set; }
		public string TG074 { get; set; }
		public string TG075 { get; set; }
		public string TG076 { get; set; }
		public string TG077 { get; set; }
		public string TG078 { get; set; }
		public string TG079 { get; set; }
		public string TG080 { get; set; }
		public string TG081 { get; set; }
		public string TG082 { get; set; }
		public string TG083 { get; set; }
		public Decimal TG084 { get; set; }
		public Decimal TG085 { get; set; }
		public string TG086 { get; set; }
		public string TG087 { get; set; }
		public string TG088 { get; set; }
		public string TG089 { get; set; }
		public string TG090 { get; set; }
		public Decimal TG091 { get; set; }
		public string TG092 { get; set; }
		public string TG093 { get; set; }
		public string TG094 { get; set; }
		public string TG095 { get; set; }
		public string TG096 { get; set; }
		public string TG097 { get; set; }
		public string TG098 { get; set; }
		public Decimal TG099 { get; set; }
		public string TG100 { get; set; }
		public Decimal TG101 { get; set; }
		public string TG102 { get; set; }
		public string TG103 { get; set; }
		public string TG104 { get; set; }
		public string TG105 { get; set; }
		public string TG106 { get; set; }
		public string TG107 { get; set; }
		public string TG108 { get; set; }
		public string TG109 { get; set; }
		public string TG110 { get; set; }
		public string TG111 { get; set; }
		public string TG112 { get; set; }
		public Decimal TG113 { get; set; }
		public Decimal TG114 { get; set; }
		public string TG115 { get; set; }
		public string TG116 { get; set; }
		public string TG117 { get; set; }
		public string TG118 { get; set; }
		public string TG119 { get; set; }
		public string TG120 { get; set; }
		public string TG121 { get; set; }
		public string TG122 { get; set; }
		public string TG123 { get; set; }
		public string TG124 { get; set; }
		public string TG125 { get; set; }
		public string TG126 { get; set; }
		public string TG127 { get; set; }
		public string TG128 { get; set; }
		public string TG129 { get; set; }
		public string TG130 { get; set; }
		public string TG131 { get; set; }
		public Decimal TG132 { get; set; }
		public string TG133 { get; set; }
		public string TG134 { get; set; }
		public string TG135 { get; set; }
		public Decimal TG136 { get; set; }
		public Decimal TG137 { get; set; }
		public Decimal TG138 { get; set; }
		public Decimal TG139 { get; set; }
		public Decimal TG140 { get; set; }
		public Decimal TG141 { get; set; }
		public string TG142 { get; set; }
		public string TG143 { get; set; }
		public string TG144 { get; set; }
		public string TG145 { get; set; }
		public string TG146 { get; set; }
		public string TG147 { get; set; }
		public string TG148 { get; set; }
		public string TG149 { get; set; }
		public string TG150 { get; set; }
		public string TG151 { get; set; }
		public Decimal TG152 { get; set; }
		public Decimal TG153 { get; set; }
		public Decimal TG154 { get; set; }
		public Decimal TG155 { get; set; }
		public string TG156 { get; set; }
		public string TG157 { get; set; }
		public string TG158 { get; set; }
		public string TG159 { get; set; }
		public string TG160 { get; set; }
		public string TG161 { get; set; }
		public string UDF01 { get; set; }
		public string UDF02 { get; set; }
		public string UDF03 { get; set; }
		public string UDF04 { get; set; }
		public string UDF05 { get; set; }
		public Decimal UDF06 { get; set; }
		public Decimal UDF07 { get; set; }
		public Decimal UDF08 { get; set; }
		public Decimal UDF09 { get; set; }
		public Decimal UDF10 { get; set; }
		public string TG200 { get; set; }
		public Decimal TG201 { get; set; }
        public Decimal TG202 { get; set; }
        public Decimal TG203 { get; set; }

    }
}
