using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace P1611706.Model
{
    public class MOCTA
	{
        public string COMPANY { get; set; }
        public string CREATOR { get; set; }
        public string USR_GROUP { get; set; }
		public string CREATE_DATE { get; set; }
		public string MODIFIER { get; set; }
		public string MODI_DATE { get; set; }
		public Decimal FLAG { get; set; }
		public string CREATE_TIME { get; set; }
		public string MODI_TIME { get; set; }
		public string TRANS_TYPE { get; set; }
		public string TRANS_NAME { get; set; }
		public string sync_date { get; set; }
		public string sync_time { get; set; }
		public string sync_mark { get; set; }
		public Decimal sync_count { get; set; }
		public string DataUser { get; set; }
		public string DataGroup { get; set; }
		public string TA001 { get; set; }
		public string TA002 { get; set; }
		public string TA003 { get; set; }
		public string TA004 { get; set; }
		public string TA005 { get; set; }
		public string TA006 { get; set; }
		public string TA007 { get; set; }
		public string TA008 { get; set; }
		public string TA009 { get; set; }
		public string TA010 { get; set; }
		public string TA011 { get; set; }
		public string TA012 { get; set; }
		public string TA013 { get; set; }
		public string TA014 { get; set; }
		public Decimal TA015 { get; set; }
		public Decimal TA016 { get; set; }
		public Decimal TA017 { get; set; }
		public Decimal TA018 { get; set; }
		public string TA019 { get; set; }
		public string TA020 { get; set; }
		public string TA021 { get; set; }
		public Decimal TA022 { get; set; }
		public string TA023 { get; set; }
		public string TA024 { get; set; }
		public string TA025 { get; set; }
		public string TA026 { get; set; }
		public string TA027 { get; set; }
		public string TA028 { get; set; }
		public string TA029 { get; set; }
		public string TA030 { get; set; }
		public Decimal TA031 { get; set; }
		public string TA032 { get; set; }
		public string TA033 { get; set; }
		public string TA034 { get; set; }
		public string TA035 { get; set; }
		public string TA036 { get; set; }
		public string TA037 { get; set; }
		public string TA038 { get; set; }
		public string TA039 { get; set; }
		public string TA040 { get; set; }
		public string TA041 { get; set; }
		public string TA042 { get; set; }
		public Decimal TA043 { get; set; }
		public string TA044 { get; set; }
		public Decimal TA045 { get; set; }
		public Decimal TA046 { get; set; }
		public Decimal TA047 { get; set; }
		public string TA048 { get; set; }
		public string TA049 { get; set; }
		public Decimal TA050 { get; set; }
		public string TA051 { get; set; }
		public string TA052 { get; set; }
		public Decimal TA053 { get; set; }
		public string TA054 { get; set; }
		public string TA055 { get; set; }
		public string TA056 { get; set; }
		public Decimal TA057 { get; set; }
		public string TA058 { get; set; }
		public string TA059 { get; set; }
		public string TA060 { get; set; }
		public string TA061 { get; set; }
		public string TA062 { get; set; }
		public string TA063 { get; set; }
		public Decimal TA064 { get; set; }
		public Decimal TA065 { get; set; }
		public string TA066 { get; set; }
		public string TA067 { get; set; }
		public string TA068 { get; set; }
		public Decimal TA069 { get; set; }
		public string TA070 { get; set; }
		public string TA071 { get; set; }
		public string TA072 { get; set; }
		public Decimal TA073 { get; set; }
		public Decimal TA074 { get; set; }
		public string TA075 { get; set; }
		public Decimal TA076 { get; set; }
		public Decimal TA077 { get; set; }
		public string TA078 { get; set; }
		public string TA079 { get; set; }
		public string TA080 { get; set; }
		public string TA081 { get; set; }
		public string TA082 { get; set; }
		public string TA083 { get; set; }
		public string TA084 { get; set; }
		public string TA085 { get; set; }
		public string TA086 { get; set; }
		public string TA087 { get; set; }
		public string TA088 { get; set; }
		public string TA089 { get; set; }
		public string TA090 { get; set; }
		public string TA091 { get; set; }
		public string TA092 { get; set; }
		public string TA093 { get; set; }
		public Decimal TA094 { get; set; }
		public string TA095 { get; set; }
		public string TA096 { get; set; }
		public string TA500 { get; set; }
		public string TA501 { get; set; }
		public string TA502 { get; set; }
		public Decimal TA503 { get; set; }
		public Decimal TA504 { get; set; }
		public string TA505 { get; set; }
		public string TA506 { get; set; }
		public string TA507 { get; set; }
		public string TA508 { get; set; }
		public string TA509 { get; set; }
		public string TA510 { get; set; }
		public string TA511 { get; set; }
		public string TA512 { get; set; }
		public string TA513 { get; set; }
		public Decimal TA514 { get; set; }
		public Decimal TA515 { get; set; }
		public Decimal TA516 { get; set; }
		public string TA520 { get; set; }
		public string TA521 { get; set; }
		public string TA522 { get; set; }
		public string TA523 { get; set; }
		public string TA524 { get; set; }
		public string TA525 { get; set; }
		public string TA526 { get; set; }
		public string TA527 { get; set; }
		public string TA528 { get; set; }
		public string TA530 { get; set; }
		public string TA531 { get; set; }
		public string TA532 { get; set; }
		public string TA533 { get; set; }
		public string TA534 { get; set; }
		public string TA535 { get; set; }
		public string TA550 { get; set; }
		public string TA551 { get; set; }
		public Decimal TA552 { get; set; }
		public string TA553 { get; set; }
		public string UDF01 { get; set; }
		public string UDF02 { get; set; }
		public string UDF03 { get; set; }
		public string UDF04 { get; set; }
		public string UDF05 { get; set; }
		public Decimal UDF06 { get; set; }
		public Decimal UDF07 { get; set; }
		public Decimal UDF08 { get; set; }
		public Decimal UDF09 { get; set; }
		public Decimal UDF10 { get; set; }

	}
}
